/*
 * Auto-generated by Frida. Please modify to match the signature of InnerSignImpl.getMtopApiSign.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call InnerSignImpl.getMtopApiSign.
   *
   * @this {object} - The Java class or instance.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Java method arguments.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onEnter(log, args, state) {
    log(`InnerSignImpl.getMtopApiSign(${args.map(JSON.stringify).join(', ')})`);
    
    // 存储参数在 this 上下文中
    this.args=args
  },

  /**
   * Called synchronously when about to return from InnerSignImpl.getMtopApiSign.
   *
   * See onEnter for details.
   *
   * @this {object} - The Java class or instance.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave(log, retval, state) {
    if (retval !== undefined) {
      // 当函数运行结束时，输出函数结果
      log(`0000000000000${this.args[0]}`)
      log(`1111111111111${this.args[1]}`)
      log(`2222222222222${this.args[2]}`)
      log(`3333333333333${this.args[3]}`)
      log(`4444444444444${this.args[4]}`)
      log(`<=555555555555555555555555555555555555555 ${retval}`);
      log(`<= ${JSON.stringify(retval)}`);
    }
  }
}
