/*
 * Auto-generated by Frida. Please modify to match the signature of InnerProtocolParamBuilderImpl.buildParams.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call InnerProtocolParamBuilderImpl.buildParams.
   *
   * @this {object} - The Java class or instance.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Java method arguments.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onEnter(log, args, state) {
      // 增加了HashMap2Str函数，将HashMap类型转换为字符串
      function HashMap2Str(params_hm) {
        var HashMap=Java.use('java.util.HashMap');
        var args_map=Java.cast(params_hm,HashMap);
        return args_map.toString();
    };
    log(`InnerProtocolParamBuilderImpl.buildParams(${args.map(JSON.stringify).join(', ')})`);
  },

  /**
   * Called synchronously when about to return from InnerProtocolParamBuilderImpl.buildParams.
   *
   * See onEnter for details.
   *
   * @this {object} - The Java class or instance.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave(log, retval, state) {
      // 增加了HashMap2Str函数，将HashMap类型转换为字符串
      function HashMap2Str(params_hm) {
        var HashMap=Java.use('java.util.HashMap');
        var args_map=Java.cast(params_hm,HashMap);
        return args_map.toString();
    };
    if (retval !== undefined) {
      log(`<= ${HashMap2Str(retval)}`);
    }
  }
}
